import { access, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

type FileSpec = {
  path: string;
  content: string;
};

const files: FileSpec[] = [
  {
    path: ".env.example",
    content: [
      "OPENAI_API_KEY=",
      "JOB_AGENT_MODEL=gpt-5",
      "JOB_AGENT_OUTPUT_DIR=./output",
      "JOB_AGENT_DATA_DIR=./data",
      "PLAYWRIGHT_HEADLESS=false",
      "",
      "JOB_AGENT_LOCAL_MODEL=deepseek-r1",
      "JOB_AGENT_USE_LOCAL=fit,answers",
      "JOB_AGENT_OLLAMA_BASE_URL=http://localhost:11434/v1",
      "",
      "# LinkedIn scout",
      "LINKEDIN_EMAIL=",
      "LINKEDIN_PASSWORD=",
      "",
    ].join("\n"),
  },
  {
    path: ".gitignore",
    content: [
      "node_modules",
      "dist",
      ".env",
      "output",
      "playwright-report",
      "test-results",
      "",
    ].join("\n"),
  },
  {
    path: "README.md",
    content: [
      "# Job Agent",
      "",
      "A personal job-search assistant that:",
      "- evaluates job fit",
      "- tailors resume content",
      "- drafts cover letters",
      "- prepares application answers",
      "- optionally fills applications in the browser",
      "",
      "## First steps",
      "1. Copy .env.example to .env",
      "2. Add your OpenAI API key",
      "3. Run: npm run init:project",
      "4. Put your source files into data/",
      "",
      "## Scout setup",
      "- Add LINKEDIN_EMAIL and LINKEDIN_PASSWORD to .env",
      "- Configure targetTitles in data/profiles/preferences.json",
      "- Run: npm run scout",
      "",
    ].join("\n"),
  },
  {
    path: "data/resumes/master_resume.md",
    content: [
      "# Master Resume",
      "",
      "Put your full, truthful resume content here.",
      "This should be your source of truth.",
      "",
    ].join("\n"),
  },
  {
    path: "data/resumes/resume-product-manager.md",
    content: [
      "# Product Manager Baseline Resume",
      "",
      "Use this file as the starting point for general product manager roles.",
      "",
      "Recommended emphasis:",
      "- roadmap ownership",
      "- cross-functional alignment",
      "- product requirements",
      "- stakeholder communication",
      "- delivery and prioritization",
      "",
      "Paste your real PM-oriented resume content here.",
      "",
    ].join("\n"),
  },
  {
    path: "data/resumes/resume-sales-engineer.md",
    content: [
      "# Sales Engineer Baseline Resume",
      "",
      "Use this file as the starting point for sales engineer, solutions engineer, and pre-sales roles.",
      "",
      "Recommended emphasis:",
      "- customer-facing technical work",
      "- discovery",
      "- demos",
      "- solution architecture",
      "- RFP support",
      "- technical deal support",
      "",
      "Paste your real sales-engineer-oriented resume content here.",
      "",
    ].join("\n"),
  },
  {
    path: "data/resumes/resume-technical-platform.md",
    content: [
      "# Technical Platform Baseline Resume",
      "",
      "Use this file as the starting point for API, platform, integration, and technical product roles.",
      "",
      "Recommended emphasis:",
      "- APIs",
      "- integrations",
      "- distributed systems",
      "- data flows",
      "- authentication",
      "- platform reliability",
      "- external technical dependencies",
      "",
      "Paste your real technical-platform-oriented resume content here.",
      "",
    ].join("\n"),
  },
  {
    path: "data/profiles/voice_profile.md",
    content: [
      "# Voice Profile",
      "",
      "Describe how you want cover letters and answers to sound.",
      "",
      "Examples:",
      "- direct",
      "- not overly polished",
      "- no fluff",
      "- no em dashes",
      "- honest about gaps",
      "",
    ].join("\n"),
  },
  {
    path: "data/profiles/preferences.json",
    content: JSON.stringify(
      {
        targetTitles: [
          "Senior Technical Product Manager",
          "Technical Product Manager",
          "Solutions Engineer",
          "Sales Engineer"
        ],
        locationPreferences: {
          remote: true,
          hybrid: true,
          onsite: false,
          preferredStates: ["FL"],
        },
        compensation: {
          minimumBaseSalary: 160000,
          preferredBaseSalary: 180000,
        },
        keywordsMustHave: ["API", "integrations", "distributed systems"],
        keywordsAvoid: ["Oracle ERP", "SAP", "pure data scientist"],
        applyModes: {
          autoSubmit: false,
          browserDraftOnly: true,
        },
      },
      null,
      2
    ) + "\n",
  },
  {
    path: "data/profiles/resume-strategy.json",
    content: JSON.stringify(
      {
        defaultResume: "data/resumes/master_resume.md",
        roleFamilies: {
          product_manager: {
            resumePath: "data/resumes/resume-product-manager.md",
            keywords: [
              "product manager",
              "roadmap",
              "prioritization",
              "stakeholders",
              "requirements"
            ]
          },
          sales_engineer: {
            resumePath: "data/resumes/resume-sales-engineer.md",
            keywords: [
              "sales engineer",
              "solutions engineer",
              "pre-sales",
              "solutions consultant",
              "technical demos",
              "RFP"
            ]
          },
          technical_platform: {
            resumePath: "data/resumes/resume-technical-platform.md",
            keywords: [
              "api",
              "platform",
              "integrations",
              "distributed systems",
              "technical product manager",
              "authentication",
              "data flows"
            ]
          }
        }
      },
      null,
      2
    ) + "\n",
  },
  {
    path: "data/profiles/accomplishments.json",
    content: JSON.stringify(
      [
        {
          id: "rdm-001",
          company: "Real Digital Media",
          role: "Senior Technical Product Manager",
          tags: ["api", "integrations", "distributed-systems", "product"],
          bullet: "Supported integration with external platforms by validating API behavior, troubleshooting request/response issues, and resolving data inconsistencies across systems",
          evidenceNote: "Resume-backed",
          confidence: "high",
        }
      ],
      null,
      2
    ) + "\n",
  },
  {
    path: "data/jobs/.gitkeep",
    content: "",
  },
  {
    path: "data/jobs/sample-job.md",
    content: [
      "# Sample Job Posting",
      "",
      "Company: Example Company",
      "Title: Senior Technical Product Manager",
      "Location: Remote",
      "",
      "Paste a real job description here before running the agents.",
      "",
    ].join("\n"),
  },
  {
    path: "data/generated/.gitkeep",
    content: "",
  },
  {
    path: "output/.gitkeep",
    content: "",
  },
  {
    path: "src/types/job.ts",
    content: [
      "export type JobPosting = {",
      "  id: string;",
      "  company: string;",
      "  title: string;",
      "  location?: string;",
      "  salaryText?: string;",
      "  url?: string;",
      "  description: string;",
      "  source?: string;",
      "  createdAt: string;",
      "};",
      "",
    ].join("\n"),
  },
  {
    path: "src/types/fit.ts",
    content: [
      "export type FitAssessment = {",
      "  score: number;",
      '  recommendation: "apply_now" | "apply_with_caution" | "skip";',
      "  strongestMatches: string[];",
      "  gaps: string[];",
      "  defensibleAngle: string;",
      "  talkingPoints: string[];",
      "};",
      "",
    ].join("\n"),
  },
  {
    path: "src/lib/env.ts",
    content: [
      'import "dotenv/config";',
      'import { z } from "zod";',
      "",
      "const envSchema = z.object({",
      '  OPENAI_API_KEY: z.string().min(1, "OPENAI_API_KEY is required"),',
      '  JOB_AGENT_MODEL: z.string().default("gpt-5"),',
      '  JOB_AGENT_OUTPUT_DIR: z.string().default("./output"),',
      '  JOB_AGENT_DATA_DIR: z.string().default("./data"),',
      "  PLAYWRIGHT_HEADLESS: z",
      '    .string()',
      '    .default("false")',
      '    .transform((v) => v === "true"),',
      "});",
      "",
      "export const env = envSchema.parse(process.env);",
      "",
    ].join("\n"),
  },
  {
    path: "src/lib/logger.ts",
    content: [
      'import pino from "pino";',
      "",
      "export const logger = pino({",
      "  transport: {",
      '    target: "pino-pretty",',
      "    options: {",
      "      colorize: true,",
      '      translateTime: "SYS:standard",',
      '      ignore: "pid,hostname",',
      "    },",
      "  },",
      "});",
      "",
    ].join("\n"),
  },
  {
    path: "src/lib/openai.ts",
    content: [
      'import OpenAI from "openai";',
      'import { env } from "./env.js";',
      "",
      "export const client = new OpenAI({",
      "  apiKey: env.OPENAI_API_KEY,",
      "});",
      "",
    ].join("\n"),
  },
  {
    path: "src/lib/fs.ts",
    content: [
      'import { mkdir, readFile, writeFile } from "node:fs/promises";',
      'import path from "node:path";',
      "",
      "export async function readText(filePath: string): Promise<string> {",
      '  return readFile(filePath, "utf8");',
      "}",
      "",
      "export async function writeText(filePath: string, content: string): Promise<void> {",
      "  await mkdir(path.dirname(filePath), { recursive: true });",
      '  await writeFile(filePath, content, "utf8");',
      "}",
      "",
    ].join("\n"),
  },
  {
    path: "src/lib/playwright.ts",
    content: [
      'import { chromium, type Browser, type Page } from "playwright";',
      'import { env } from "./env.js";',
      "",
      "export async function withBrowser<T>(",
      "  fn: (page: Page, browser: Browser) => Promise<T>",
      "): Promise<T> {",
      "  const browser = await chromium.launch({ headless: env.PLAYWRIGHT_HEADLESS });",
      "  const page = await browser.newPage();",
      "  try {",
      "    return await fn(page, browser);",
      "  } finally {",
      "    await browser.close();",
      "  }",
      "}",
      "",
    ].join("\n"),
  },
  {
    path: "src/prompts/evaluate-fit.txt",
    content: [
      "You are evaluating job fit for the user's job search.",
      "",
      "Rules:",
      "- Use only the supplied resume and accomplishments",
      "- Do not invent experience",
      "- Separate direct match from adjacent experience",
      "- Be honest about gaps",
      "- Recommend one of: apply_now, apply_with_caution, skip",
      "",
      "Return strict JSON with:",
      "{",
      '  "score": number,',
      '  "recommendation": "apply_now" | "apply_with_caution" | "skip",',
      '  "strongestMatches": string[],',
      '  "gaps": string[],',
      '  "defensibleAngle": string,',
      '  "talkingPoints": string[]',
      "}",
      "",
    ].join("\n"),
  },
  {
    path: "src/prompts/tailor-resume.txt",
    content: [
      "Tailor the resume to the job posting using only supplied facts.",
      "Do not invent tools, ownership, or achievements.",
      "Preserve a natural tone and keep statements defensible.",
      "",
    ].join("\n"),
  },
  {
    path: "src/prompts/draft-cover-letter.txt",
    content: [
      "Draft a concise, natural cover letter.",
      "Avoid robotic praise.",
      "Use the user's voice profile.",
      "Do not overclaim.",
      "",
    ].join("\n"),
  },
  {
    path: "src/prompts/prepare-application.txt",
    content: [
      "Prepare likely application answers based only on provided materials.",
      "Flag anything that needs manual user review.",
      "",
    ].join("\n"),
  },
  {
    path: "src/agents/evaluate_fit.ts",
    content: [
      'import path from "node:path";',
      'import { readText, writeText } from "../lib/fs.js";',
      'import { client } from "../lib/openai.js";',
      'import { env } from "../lib/env.js";',
      'import { logger } from "../lib/logger.js";',
      "",
      "async function main() {",
      '  const jobPath = process.argv[2] || path.join(env.JOB_AGENT_DATA_DIR, "jobs", "sample-job.md");',
      '  const resumePath = path.join(env.JOB_AGENT_DATA_DIR, "resumes", "master_resume.md");',
      '  const accomplishmentsPath = path.join(env.JOB_AGENT_DATA_DIR, "profiles", "accomplishments.json");',
      '  const promptPath = path.join("src", "prompts", "evaluate-fit.txt");',
      "",
      "  const [jobDescription, resume, accomplishments, systemPrompt] = await Promise.all([",
      "    readText(jobPath),",
      "    readText(resumePath),",
      "    readText(accomplishmentsPath),",
      "    readText(promptPath),",
      "  ]);",
      "",
      "  const userContent = [",
      '    "Resume:",',
      "    resume,",
      '    "",',
      '    "Accomplishments:",',
      "    accomplishments,",
      '    "",',
      '    "Job Description:",',
      "    jobDescription,",
      '  ].join("\\n");',
      "",
      "  const response = await client.responses.create({",
      "    model: env.JOB_AGENT_MODEL,",
      "    input: [",
      '      { role: "system", content: systemPrompt },',
      '      { role: "user", content: userContent },',
      "    ],",
      "  });",
      "",
      "  const text = response.output_text;",
      '  const outPath = path.join(env.JOB_AGENT_OUTPUT_DIR, "fit-report.json");',
      "  await writeText(outPath, text);",
      '  logger.info({ outPath }, "Fit report written");',
      "  console.log(text);",
      "}",
      "",
      "main().catch((err) => {",
      "  console.error(err);",
      "  process.exit(1);",
      "});",
      "",
    ].join("\n"),
  },
  {
    path: "src/agents/tailor_resume.ts",
    content: [
      'import path from "node:path";',
      'import { readText, writeText } from "../lib/fs.js";',
      'import { client } from "../lib/openai.js";',
      'import { env } from "../lib/env.js";',
      "",
      "async function main() {",
      '  const jobPath = process.argv[2] || path.join(env.JOB_AGENT_DATA_DIR, "jobs", "sample-job.md");',
      '  const resumePath = path.join(env.JOB_AGENT_DATA_DIR, "resumes", "master_resume.md");',
      '  const voicePath = path.join(env.JOB_AGENT_DATA_DIR, "profiles", "voice_profile.md");',
      '  const promptPath = path.join("src", "prompts", "tailor-resume.txt");',
      "",
      "  const [jobDescription, resume, voice, systemPrompt] = await Promise.all([",
      "    readText(jobPath),",
      "    readText(resumePath),",
      "    readText(voicePath),",
      "    readText(promptPath),",
      "  ]);",
      "",
      "  const userContent = [",
      '    "Voice profile:",',
      "    voice,",
      '    "",',
      '    "Master resume:",',
      "    resume,",
      '    "",',
      '    "Job Description:",',
      "    jobDescription,",
      '  ].join("\\n");',
      "",
      "  const response = await client.responses.create({",
      "    model: env.JOB_AGENT_MODEL,",
      "    input: [",
      '      { role: "system", content: systemPrompt },',
      '      { role: "user", content: userContent },',
      "    ],",
      "  });",
      "",
      '  const outPath = path.join(env.JOB_AGENT_OUTPUT_DIR, "tailored-resume.md");',
      "  await writeText(outPath, response.output_text);",
      "  console.log(response.output_text);",
      "}",
      "",
      "main().catch((err) => {",
      "  console.error(err);",
      "  process.exit(1);",
      "});",
      "",
    ].join("\n"),
  },
  {
    path: "src/agents/draft_cover_letter.ts",
    content: [
      'import path from "node:path";',
      'import { readText, writeText } from "../lib/fs.js";',
      'import { client } from "../lib/openai.js";',
      'import { env } from "../lib/env.js";',
      "",
      "async function main() {",
      '  const jobPath = process.argv[2] || path.join(env.JOB_AGENT_DATA_DIR, "jobs", "sample-job.md");',
      '  const resumePath = path.join(env.JOB_AGENT_DATA_DIR, "resumes", "master_resume.md");',
      '  const voicePath = path.join(env.JOB_AGENT_DATA_DIR, "profiles", "voice_profile.md");',
      '  const promptPath = path.join("src", "prompts", "draft-cover-letter.txt");',
      "",
      "  const [jobDescription, resume, voice, systemPrompt] = await Promise.all([",
      "    readText(jobPath),",
      "    readText(resumePath),",
      "    readText(voicePath),",
      "    readText(promptPath),",
      "  ]);",
      "",
      "  const userContent = [",
      '    "Voice profile:",',
      "    voice,",
      '    "",',
      '    "Resume:",',
      "    resume,",
      '    "",',
      '    "Job Description:",',
      "    jobDescription,",
      '  ].join("\\n");',
      "",
      "  const response = await client.responses.create({",
      "    model: env.JOB_AGENT_MODEL,",
      "    input: [",
      '      { role: "system", content: systemPrompt },',
      '      { role: "user", content: userContent },',
      "    ],",
      "  });",
      "",
      '  const outPath = path.join(env.JOB_AGENT_OUTPUT_DIR, "cover-letter.md");',
      "  await writeText(outPath, response.output_text);",
      "  console.log(response.output_text);",
      "}",
      "",
      "main().catch((err) => {",
      "  console.error(err);",
      "  process.exit(1);",
      "});",
      "",
    ].join("\n"),
  },
  {
    path: "src/agents/prepare_application.ts",
    content: [
      'import path from "node:path";',
      'import { readText, writeText } from "../lib/fs.js";',
      'import { client } from "../lib/openai.js";',
      'import { env } from "../lib/env.js";',
      "",
      "async function main() {",
      '  const jobPath = process.argv[2] || path.join(env.JOB_AGENT_DATA_DIR, "jobs", "sample-job.md");',
      '  const resumePath = path.join(env.JOB_AGENT_DATA_DIR, "resumes", "master_resume.md");',
      '  const preferencesPath = path.join(env.JOB_AGENT_DATA_DIR, "profiles", "preferences.json");',
      '  const promptPath = path.join("src", "prompts", "prepare-application.txt");',
      "",
      "  const [jobDescription, resume, preferences, systemPrompt] = await Promise.all([",
      "    readText(jobPath),",
      "    readText(resumePath),",
      "    readText(preferencesPath),",
      "    readText(promptPath),",
      "  ]);",
      "",
      "  const userContent = [",
      '    "Resume:",',
      "    resume,",
      '    "",',
      '    "Preferences:",',
      "    preferences,",
      '    "",',
      '    "Job Description:",',
      "    jobDescription,",
      '  ].join("\\n");',
      "",
      "  const response = await client.responses.create({",
      "    model: env.JOB_AGENT_MODEL,",
      "    input: [",
      '      { role: "system", content: systemPrompt },',
      '      { role: "user", content: userContent },',
      "    ],",
      "  });",
      "",
      '  const outPath = path.join(env.JOB_AGENT_OUTPUT_DIR, "application-answers.md");',
      "  await writeText(outPath, response.output_text);",
      "  console.log(response.output_text);",
      "}",
      "",
      "main().catch((err) => {",
      "  console.error(err);",
      "  process.exit(1);",
      "});",
      "",
    ].join("\n"),
  },
  {
    path: "src/agents/submit_application.ts",
    content: [
      'import path from "node:path";',
      'import { withBrowser } from "../lib/playwright.js";',
      "",
      "async function main() {",
      "  const url = process.argv[2];",
      "  if (!url) {",
      '    throw new Error("Usage: npm run apply:dry -- <application-url>");',
      "  }",
      "",
      "  await withBrowser(async (page) => {",
      '    await page.goto(url, { waitUntil: "domcontentloaded" });',
      '    console.log("Opened application page in dry-run mode:", url);',
      '    await page.screenshot({ path: path.join("output", "apply-dry-run.png"), fullPage: true });',
      "  });",
      "}",
      "",
      "main().catch((err) => {",
      "  console.error(err);",
      "  process.exit(1);",
      "});",
      "",
    ].join("\n"),
  },
  {
    path: "src/agents/scout.ts",
    content: [
      'console.log("Scout agent placeholder. Start with manual job URLs and saved job descriptions first.");',
      "",
    ].join("\n"),
  },
  {
    path: "src/workflows/job_pipeline.ts",
    content: [
      'console.log("Workflow placeholder. Add orchestration after the individual agents work well.");',
      "",
    ].join("\n"),
  },
];

async function ensureDir(filePath: string): Promise<void> {
  await mkdir(path.dirname(filePath), { recursive: true });
}

async function exists(filePath: string): Promise<boolean> {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function main() {
  for (const file of files) {
    await ensureDir(file.path);

    const alreadyExists = await exists(file.path);
    if (alreadyExists) {
      console.log("skip  " + file.path);
      continue;
    }

    await writeFile(file.path, file.content, "utf8");
    console.log("create " + file.path);
  }

  console.log("");
  console.log("Project scaffolding complete.");
  console.log("Next:");
  console.log("1. Copy .env.example to .env");
  console.log("2. Add OPENAI_API_KEY");
  console.log("3. Put a job description into data/jobs/sample-job.md");
  console.log("4. Run: npm run fit -- data/jobs/sample-job.md");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});